spring:
  application:
    name: spring-boot-demo
 #    数据源配置
  datasource:
      url: jdbc:mysql://localhost:3306/college_student?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: yrf246810
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 2
        pool-name: SchoolRunHikariPool

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.pojo.entity
  configuration:
    map-underscore-to-camel-case: true


   #日志级别
logging:
  level:
    com.example.demo: DEBUG
    # JWT配置
jwt:
  admin:
        # 使用至少32字符的密钥
    admin-secret-key: PaQi404Notfound_key_32_characters_long_xxxx
        # 设置jwt过期时间
    admin-ttl: 7200000
        # 设置前端传递过来的令牌名称
    admin-token-name: token